Controllers/AdminController.cs
using FPTBook.Data;
using FPTBook.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;

namespace FPTBook.Controllers
{
    public class AdminController : Controller
    {
        private readonly ApplicationDbContext context;
        public AdminController(ApplicationDbContext context)
        {
            this.context = context;
        }

        [Authorize(Roles = "Administrator")]
        public IActionResult Index()
        {
            var requests = context.Requests.ToList();
            return View(requests);
        }

        [Authorize(Roles = "Administrator")]
        public IActionResult ApproveRequest(int id)
        {
            var request = new Category();
            request.Name = context.Requests.Where(x=> x.Id == id).First().Name;
            request.Description = context.Requests.Where(x=> x.Id == id).First().Description;
            TempData["Message"] = "New Category has been added";
            var category = context.Categories.Add(request);
            context.SaveChanges();
            var req =  context.Requests.Find(id);
            context.Requests.Remove(req);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Administrator")]
        public IActionResult RejectRequest(int? id)
        {
            if(id == null) return NotFound();
            else
            {
                TempData["Message"] = "Request has been rejected.";
                var request = context.Requests.Find(id);
                context.Requests.Remove(request);
                context.SaveChanges();
                return RedirectToAction("Index");
            }
        }

        [Authorize(Roles = "Administrator")]
        public IActionResult Customer()
        {
            var userIds = context.UserRoles.Where(r => r.RoleId == "C").ToList();
            var userId = "";
            var customer = context.Users.Where(c => c.Id == "-1").ToList();
            for(int i=0; i<userIds.Count();i++)
            {
                userId = userIds.ElementAt(i).UserId;
                customer.Add(context.Users.Where(c => c.Id == userId).First());
            }
            return View(customer);
        }

        [Authorize(Roles = "Administrator")]
        public IActionResult BookOwner()
        {
            var userIds = context.UserRoles.Where(r => r.RoleId == "B").ToList();
            var userId = "";
            var bookowner = context.Users.Where(b => b.Id == "-1").ToList();
            for (int i=0; i< userIds.Count(); i++)
            {
                userId = userIds.ElementAt(i).UserId;
                bookowner.Add(context.Users.Where(c => c.Id == userId).First());
            }
            return View(bookowner);
        }
    }
}

//GET LIST USER ID
//GET USER BY USER ID

Controllers/BookController.cs
using FPTBook.Data;
using FPTBook.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace FPTBook.Controllers
{
    public class BookController : Controller
    {
        public readonly ApplicationDbContext context;

        public BookController(ApplicationDbContext context)
        {
            this.context = context;
        }

        [Authorize(Roles = "BookOwner")]
        public IActionResult Index()
        {
            var categories = context.Categories.ToList();
            ViewBag.Categories = categories;
            return View(context.Books.ToList());
        }

        public IActionResult Detail(int id)
        {
            var categories = context.Categories.ToList();
            var book = context.Books.Find(id);
            return View(book);
        }

        [Authorize(Roles = "BookOwner")]
        [HttpGet]
        public IActionResult Add()
        {
            var categories = context.Categories.ToList();
            ViewBag.Categories = categories;
            return View();
        }

        [HttpPost]
        public IActionResult Add(Book book)
        {
            if(ModelState.IsValid)
            {
                context.Books.Add(book);
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Categories = context.Categories.ToList();
            return View(book);
        }

        [Authorize(Roles = "BookOwner")]
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var categories = context.Categories.ToList();
            ViewBag.Categories = categories;
            var books = context.Books.Find(id);
            return View(books);
        }

        [HttpPost]
        public IActionResult Edit(Book book)
        {
            if(ModelState.IsValid)
            {
                context.Books.Update(book);
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Categories = context.Categories.ToList();
            return View(book);
        }

        [Authorize(Roles = "BookOwner")]
        public IActionResult Delete(int? id)
        {
            if(id == null) return NotFound();
            else
            {
                   var book = context.Books.Find(id);
                   context.Books.Remove(book);
                   context.SaveChanges();
                   return RedirectToAction("Index");
            }
        }

     

       
    }
}

Controllers/ClientController.cs
using FPTBook.Data;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Data;
using System.Linq;

namespace FPTBook.Controllers
{

    public class ClientController : Controller
    {
        public readonly ApplicationDbContext context;
        public ClientController(ApplicationDbContext context)
        {
            this.context = context;
        }

        [Route("/")]
        public IActionResult Index()
        {
            return View(context.Books.ToList());
        }

        public IActionResult About()
        {
            return View();
        }

        public IActionResult Blog()
        {
            return View();
        }

        public IActionResult Store()
        {
            return View(context.Books.ToList());
        }

        public IActionResult Detail(int id)
        {
            var cate = context.Categories.ToList();
            var books = context.Books.Find(id);
            return View(books);
        }
        
        [HttpPost]
        public IActionResult Search(string keyword)
        {
            var books = context.Books.Where(x=>x.Title.Contains(keyword)).ToList();
            if(books.Count == 0)
            {
                TempData["Message"] = "No book found";
            }
            return View("Store", books);
        }
       
        public IActionResult SortAscName()
        {
            var books = context.Books.OrderBy(x => x.Title).ToList();
            return View("Store", books);
        }
        public IActionResult SortDscName()
        {
            var books = context.Books.OrderByDescending(x => x.Title).ToList();
            return View("Store", books);
        }

        public IActionResult SortAscPrice()
        {
            var books = context.Books.OrderBy(x => x.Price).ToList();
            return View("Store", books);
        }

        public IActionResult SortDscPrice()
        {
            var books = context.Books.OrderByDescending(x => x.Price).ToList();
            return View("Store", books);
        }

    }
}

Controllers/OrderController.cs
using FPTBook.Data;
using FPTBook.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Net;

namespace FPTBook.Controllers
{
    public class OrderController : Controller
    {
        public ApplicationDbContext context { get; set; }
        public OrderController(ApplicationDbContext context)
        {
            this.context = context;
        }

        [Authorize (Roles = "Customer")]
        public IActionResult MakeOrder(int id, int quantity, string customerName, int price)
        {
            TempData["ok"] = "Order successfully !";
            var order = new Order();
            order.Status = -1;
            order.Price = price;
            order.OrderQuantity = quantity;
            order.BookId = id;
            order.Customer = customerName;
            order.OrderName = context.Books.Find(id).Title;
            order.OrderPrice = (context.Books.Find(id).Price)*quantity;
            
            context.Orders.Add(order);
            context.SaveChanges();
            return View(order);
        }

        public IActionResult CancelOrder(int id)
        {
            var order = context.Orders.Find(id);
            context.Orders.Remove(order);
            context.SaveChanges();
            return Redirect("~/Client/Store");
        }

        //[Authorize(Roles = "BookOwner")]
        //[Authorize(Roles = "Customer")]
        public IActionResult Record()
        {
            var customerOrder = context.Orders.ToList();
           
            return View(customerOrder) ;
        }

        //Authorize (Roles = "BookOwner")]
        //[Authorize(Roles = "Customer")]
        public IActionResult Approve(int id, int quantity, int bookId)
        {
            TempData["approve"] = "Order has been approved";
            var order = context.Orders.Find(id);
            var name = context.Orders.Where(x=>x.Id == id).First().OrderName;
            context.Books.Where(x => x.Title == name).First().Quantity -= quantity;
            context.Orders.Where(x => x.Id == id).First().Status = 1;
            context.SaveChanges();
            return RedirectToAction("Record");
        }

        //[Authorize(Roles = "BookOwner")]
        public IActionResult Cancel(int id)
        {
            TempData["cancel"] = "Order has been cancelled";
            var order = context.Orders.Find(id);
            context.Orders.Where(x => x.Id == id).First().Status = 0;
            context.SaveChanges();
            return RedirectToAction("Record");

        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Basic -->
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>@ViewData["Title"] - FPTBook</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="~/assets/img/favicon.png" rel="icon">
    <link href="~/assets/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="~/assets/vendor/aos/aos.css" rel="stylesheet">
    <link href="~/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="~/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="~/assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
    <link href="~/assets/vendor/remixicon/remixicon.css" rel="stylesheet">
    <link href="~/assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="~/assets/css/style.css" rel="stylesheet">

    <!-- CSS only -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <!-- bootstrap core css -->
    <link rel="stylesheet" type="text/css" href="~/css/bootstrap.css" />
    <!-- font awesome style -->
    <link href="~/css/font-awesome.min.css" rel="stylesheet" />

    <!-- Custom styles for this template -->
    <link href="~/css/style.css" rel="stylesheet" />
    <!-- responsive style -->
    <link href="~/css/responsive.css" rel="stylesheet" />
    <script src="https://kit.fontawesome.com/6b57bdf61a.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css"
          integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous" />
</head>

@* navbar-light bg-white border-bottom box-shadow mb-3"*@
  <body>
    <header >
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm"
             style="background-color:#778899 ">
            <div class="container" >
                <a class="navbar-brand text-light" asp-area="" asp-controller="Client" asp-action="Index"> FptBookShop</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1" style="margin-left:100px">
                        @if(User.Identity.IsAuthenticated && User.IsInRole("Administrator"))
                        {
                            <li class="nav-item" style="margin-right:30px">
                                <a style="font-size: 20px; font-weight: bold" class="nav-link text-light" asp-area="" asp-controller="Admin" asp-action="Index">Request Approval</a>
                            </li>
                            <li class="nav-item" style="margin-right:30px">
                                <a style="font-size: 20px; font-weight: bold" class="nav-link text-light" asp-area="" asp-controller="Category" asp-action="Index">Category</a>
                            </li>
                            <li class="nav-item" >
                                <a style="font-size: 20px; font-weight: bold" class="nav-link text-light" asp-area="" asp-controller="Admin" asp-action="Customer">User Account</a>
                            </li>
                           
                        }
                        @if (User.Identity.IsAuthenticated && User.IsInRole("BookOwner"))
                        {
                            <li class="nav-item" style="margin-right:30px">
                                <a style="font-size: 20px; font-weight: bold" class="nav-link text-light" asp-area="" asp-controller="Book" asp-action="Index">Book</a>
                            </li>
                            <li class="nav-item" style="margin-right:30px">
                                <a style="font-size: 20px; font-weight: bold" class="nav-link text-light" asp-area="" asp-controller="Category" asp-action="Request" >Request</a>
                            </li>
                            <li class="nav-item">
                                <a style="font-size: 20px; font-weight: bold" class="nav-link text-light" style="margin-right:30px" asp-area="" asp-controller="Category" asp-action="Index">Category</a>
                            </li>
                            <li class="nav-item">
                                <a style="font-size: 20px; font-weight: bold" class="nav-link text-light" asp-area="" asp-controller="Order" asp-action="Record">Order</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
        </header>



    <div class="container" style="margin-top:80px">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer id="footer">
        <div class="footer-top">
            <div class="container">
                <div class="row">

                    <div class="col-lg-3 col-md-6">
                        <div class="footer-info">
                            <h3>FptBookShop</h3>
                            <p>
                                2 Pham Van Bach Street <br>
                                Dich Vong, Cau Giay, Ha Noi<br><br>
                                <strong>Phone:</strong> +84 367608114<br>
                                <strong>Email:</strong> doanvanchien06022002@gmail.com<br>
                            </p>
                            <div class="social-links mt-3">
                                <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
                                <a href="https://www.facebook.com/profile.php?id=100008184165996" class="facebook"><i class="bx bxl-facebook"></i></a>
                                <a href="https://www.instagram.com/chiendv2002/" class="instagram"><i class="bx bxl-instagram"></i></a>
                                <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
                                <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-2 col-md-6 footer-links">
                        <h4>Useful Links</h4>
                        <ul>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Home</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">About us</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Services</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Terms of service</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Privacy policy</a></li>
                        </ul>
                    </div>

                    <div class="col-lg-3 col-md-6 footer-links">
                        <h4>Our Services</h4>
                        <ul>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Web Design</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Web Development</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Product Management</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Marketing</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Graphic Design</a></li>
                        </ul>
                    </div>

                    <div class="col-lg-4 col-md-6 footer-newsletter">
                        <h4>Our Newsletter</h4>
                        <p>Always update quickly and accurately</p>
                        <form action="" method="post">
                            <input type="email" name="email"><input type="submit" value="Subscribe">
                        </form>

                    </div>

                </div>
            </div>
        </div>

        <div class="container">
            <div class="copyright">
                &copy; Copyright <strong><span>FptBookShop</span></strong>. All Rights Reserved
            </div>
            <div class="credits">
                <!-- All the links in the footer should remain intact. -->
                <!-- You can delete the links only if you purchased the pro version. -->
                <!-- Licensing information: https://bootstrapmade.com/license/ -->
                <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/gp-free-multipurpose-html-bootstrap-template/ -->
                Designed by <a href="https://www.facebook.com/profile.php?id=100008184165996">Chien</a>
            </div>
        </div>
    </footer><!-- End Footer -->

    <div id="preloader"></div>
    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

    <!-- Vendor JS Files -->
    <script src="~/assets/vendor/purecounter/purecounter_vanilla.js"></script>
    <script src="~/assets/vendor/aos/aos.js"></script>
    <script src="~/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/assets/vendor/glightbox/js/glightbox.min.js"></script>
    <script src="~/assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
    <script src="~/assets/vendor/swiper/swiper-bundle.min.js"></script>
    <script src="~/assets/vendor/php-email-form/validate.js"></script>

    <!-- Template Main JS File -->
    <script src="~/assets/js/main.js"></script>
    @RenderSection("Scripts", required: false)
</body>

</html>